---
collections:
  - name: community.docker
    version: 5.0.2
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 10.1.0
  - name: prometheus.prometheus
    version: 0.27.4
  - name: grafana.grafana
    version: 6.0.6
