---
roles:
  - name: geerlingguy.docker
    version: 7.8.0
  - name: geerlingguy.security
    version: 3.0.0
  - name: geerlingguy.firewall
    version: 2.7.0
  - name: geerlingguy.ntp
    version: 3.0.0
