# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/inventory.json
---
all:
  children:
    vps:
      hosts:
        # 腾讯云轻量服务器 硅谷
        lab-sfo-txy-01:
          ansible_port: "{{ security_ssh_port }}"
          # ansible_host 与 ansible_user 由 host_vars/lab-sfo-txy-01/secrets.yml 提供（使用 Vault 加密）
