---
dependency:
  name: galaxy
  options:
    ignore-errors: true
    role-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/collections/requirements.yml
driver:
  name: vagrant
  provider:
    name: libvirt
scenario:
  name: default

platforms:
  - name: debian13
    box: jtarpley/debian13_base
    memory: 1024
    cpus: 2
    groups:
      - vps
provisioner:
  name: ansible
  inventory:
    links:
      host_vars: host_vars
      group_vars: group_vars
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: prepare.yml
    verify: verify.yml
  env:
    PATH: "${MOLECULE_PROJECT_DIRECTORY}/.venv/bin:${PATH}"
verifier:
  name: ansible
