---
dependency:
  name: galaxy
  options:
    ignore-errors: true
    role-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/collections/requirements.yml
driver:
  name: docker
scenario:
  name: default

platforms:
  - name: debian13
    image: "bernylinville/docker-debian13-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    groups:
      - vps
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
  inventory:
    links:
      host_vars: host_vars
      group_vars: group_vars
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: prepare.yml
    verify: verify.yml
  env:
    PATH: "${MOLECULE_PROJECT_DIRECTORY}/.venv/bin:${PATH}"
verifier:
  name: ansible
