---
- name: Verify hardened baseline
  hosts: all
  become: true
  tasks:
    - name: Check fail2ban service status
      ansible.builtin.command: systemctl is-active fail2ban
      register: fail2ban_status
      changed_when: false

    - name: Assert fail2ban is active
      ansible.builtin.assert:
        that:
          - fail2ban_status.stdout.strip() == "active"
        fail_msg: "fail2ban service is not active"

    - name: Inspect UFW status output
      ansible.builtin.command: ufw status
      register: ufw_status
      changed_when: false

    - name: Assert UFW is active and SSH port allowed
      ansible.builtin.assert:
        that:
          - "Status: active" in ufw_status.stdout
          - ufw_status.stdout is search('22/tcp')
        fail_msg: "UFW is not active or SSH port missing"
