---
- name: Verify hardened baseline
  hosts: all
  become: true
  tasks:
    - name: Check fail2ban service status
      ansible.builtin.command: systemctl is-active fail2ban
      register: fail2ban_status
      changed_when: false

    - name: Assert fail2ban is active
      ansible.builtin.assert:
        that:
          - fail2ban_status.stdout.strip() == "active"
        fail_msg: "fail2ban service is not active"

    - name: Check firewall service status
      ansible.builtin.command: systemctl is-active firewall
      register: firewall_status
      changed_when: false

    - name: Assert firewall is active
      ansible.builtin.assert:
        that:
          - firewall_status.stdout.strip() == "active"
        fail_msg: "firewall service is not active"

    - name: Check iptables rules
      ansible.builtin.command: iptables -L INPUT -n
      register: iptables_status
      changed_when: false
      become: true

    - name: Assert SSH port is allowed in iptables
      ansible.builtin.assert:
        that:
          - iptables_status.stdout is search('dpt:22')
        fail_msg: "SSH port 22 is not allowed in iptables"
